declare namespace NodeJS {
	interface ProcessEnv {
		APP_VARIANT: string;
		EXPO_PUBLIC_SUPABASE_URL: string;
		EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY: string;
		EXPO_PUBLIC_REVENUECAT_IOS_API_KEY: string;
		EXPO_PUBLIC_REVENUECAT_ANDROID_API_KEY: string;
		EXPO_PUBLIC_REVENUECAT_PRO_ENTITLEMENT_ID: string;
		GOOGLE_MAPS_API_KEY: string;
	}
}
