declare namespace NodeJS {
	interface ProcessEnv {
		APP_VARIANT: string;
		EXPO_PUBLIC_SUPABASE_URL: string;
		EXPO_PUBLIC_SUPABASE_KEY: string;
		EXPO_PUBLIC_REVENUECAT_IOS_API_KEY: string;
		EXPO_PUBLIC_REVENUECAT_ANDROID_API_KEY: string;
		EXPO_PUBLIC_REVENUECAT_PLUS_ENTITLEMENT_ID: string;
		EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID: string;
		EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID: string;
		GOOGLE_MAPS_API_KEY: string;
	}
}
