import type { MockTrip, TimelineItem } from '@/types/types';

const p = (id: string, seed: string) => ({ id, url: `https://picsum.photos/seed/${seed}/800/600` });

const santoriniTimeline: TimelineItem[] = [
	{
		id: 'tl-1',
		trip_id: '6',
		type: 'transport',
		title: 'Flight to Athens',
		description: 'KRK → ATH',
		starts_at: '2026-07-10T06:30:00Z',
		ends_at: '2026-07-10T10:00:00Z',
		cost_amount: 320,
		cost_currency: 'PLN',
		split_type: 'split_equally',
		created_by: 'u-001',
		created_at: '2026-05-01T10:00:00Z',
		updated_at: '2026-05-01T10:00:00Z',
		address: null,
		latitude: null,
		location_label: null,
		longitude: null,
		paid_by: null,
		updated_by: null,
	},
	{
		id: 'tl-2',
		trip_id: '6',
		type: 'transport',
		title: 'Ferry to Santorini',
		description: 'Piraeus → Athinios Port',
		starts_at: '2026-07-10T14:00:00Z',
		ends_at: '2026-07-10T21:30:00Z',
		cost_amount: 85,
		cost_currency: 'EUR',
		split_type: 'split_equally',
		created_by: 'u-001',
		created_at: '2026-05-01T10:00:00Z',
		updated_at: '2026-05-01T10:00:00Z',
		address: null,
		latitude: null,
		location_label: null,
		longitude: null,
		paid_by: null,
		updated_by: null,
	},
	{
		id: 'tl-3',
		trip_id: '6',
		type: 'stay',
		title: 'Cave Hotel in Oia',
		description: 'Sea view, cliff-side suite',
		starts_at: '2026-07-10T22:00:00Z',
		ends_at: '2026-07-17T11:00:00Z',
		cost_amount: 1200,
		cost_currency: 'EUR',
		split_type: 'split_equally',
		created_by: 'u-001',
		created_at: '2026-05-01T10:00:00Z',
		updated_at: '2026-05-01T10:00:00Z',
		address: null,
		latitude: null,
		location_label: null,
		longitude: null,
		paid_by: null,
		updated_by: null,
	},
	{
		id: 'tl-4',
		trip_id: '6',
		type: 'activity',
		title: 'Sunset at Oia Castle',
		starts_at: '2026-07-11T19:00:00Z',
		split_type: 'informational',
		created_by: 'u-001',
		created_at: '2026-05-01T10:00:00Z',
		updated_at: '2026-05-01T10:00:00Z',
		address: null,
		cost_amount: null,
		cost_currency: null,
		description: null,
		ends_at: null,
		latitude: null,
		location_label: null,
		longitude: null,
		paid_by: null,
		updated_by: null,
	},
	{
		id: 'tl-5',
		trip_id: '6',
		type: 'food',
		title: 'Dinner at Ammoudi Bay',
		description: 'Fresh seafood, sea view',
		starts_at: '2026-07-12T20:00:00Z',
		cost_amount: 45,
		cost_currency: 'EUR',
		split_type: 'split_equally',
		created_by: 'f1',
		created_at: '2026-05-01T12:00:00Z',
		updated_at: '2026-05-01T12:00:00Z',
		address: null,
		ends_at: null,
		latitude: null,
		location_label: null,
		longitude: null,
		paid_by: null,
		updated_by: null,
	},
];

export const MOCK_TRIPS: MockTrip[] = [
	{
		id: '1',
		status: 'saved',
		title: 'Roman Holiday',
		city: 'Rome',
		country: 'Italy',
		flag: '🇮🇹',
		startDate: '2025-03-15',
		endDate: '2025-03-22',
		photoCount: 47,
		note: 'The Colosseum at sunset was unbelievable. Best carbonara of my life. Spent way too long at the Forum.',
		photos: [p('1-1', 'rome-forum'), p('1-2', 'rome-colosseum'), p('1-3', 'rome-trevi')],
		coverPhoto: p('1-1', 'rome-forum'),
		participants: [
			{ id: 'f1', name: 'Emma Wilson', gender: 'female', avatar_index: 0, status: 'confirmed' },
			{ id: 'f2', name: 'Marco Rossi', gender: 'male', avatar_index: 0, status: 'confirmed' },
		],
		latitude: 41.8902,
		longitude: 12.4922,
	},
	{
		id: '2',
		status: 'saved',
		title: 'Lisbon in Bloom',
		city: 'Lisbon',
		country: 'Portugal',
		flag: '🇵🇹',
		startDate: '2025-05-01',
		endDate: '2025-05-07',
		photoCount: 31,
		note: 'Tram 28 through the old city. Pastéis de nata still warm from the bakery. Views from the castle were worth every step.',
		photos: [p('2-1', 'lisbon-tram'), p('2-2', 'lisbon-alfama'), p('2-3', 'lisbon-belem')],
		coverPhoto: p('2-1', 'lisbon-tram'),
		participants: [{ id: 'f3', name: 'Jake Thompson', gender: 'male', avatar_index: 2, status: 'confirmed' }],
		latitude: 38.7223,
		longitude: -9.1393,
	},
	{
		id: '3',
		status: 'saved',
		title: 'Tokyo Nights',
		city: 'Tokyo',
		country: 'Japan',
		flag: '🇯🇵',
		startDate: '2024-10-10',
		endDate: '2024-10-20',
		photoCount: 89,
		note: 'Shibuya at 2am will never leave my mind. Tsukiji breakfast. Could have stayed forever.',
		photos: [p('3-1', 'tokyo-shibuya'), p('3-2', 'tokyo-temple'), p('3-3', 'tokyo-night'), p('3-4', 'tokyo-street')],
		coverPhoto: p('3-1', 'tokyo-shibuya'),
		participants: [
			{ id: 'f1', name: 'Emma Wilson', gender: 'female', avatar_index: 0, status: 'confirmed' },
			{ id: 'f4', name: 'Sophia Chen', gender: 'female', avatar_index: 3, status: 'confirmed' },
			{ id: 'f5', name: 'Lucas Müller', gender: 'male', avatar_index: 5, status: 'confirmed' },
		],
		latitude: 35.6762,
		longitude: 139.6503,
	},
	{
		id: '4',
		status: 'saved',
		title: 'Barcelona Weekend',
		city: 'Barcelona',
		country: 'Spain',
		flag: '🇪🇸',
		startDate: '2025-01-10',
		endDate: '2025-01-12',
		photoCount: 23,
		note: 'Gaudí changed how I see architecture forever. Beach day after Sagrada Família.',
		photos: [p('4-1', 'barcelona-sagrada'), p('4-2', 'barcelona-beach')],
		coverPhoto: p('4-1', 'barcelona-sagrada'),
		participants: [],
		latitude: 41.3874,
		longitude: 2.1686,
	},
	{
		id: '5',
		status: 'saved',
		title: 'NYC Winter',
		city: 'New York',
		country: 'United States',
		flag: '🇺🇸',
		startDate: '2024-12-20',
		endDate: '2024-12-27',
		photoCount: 62,
		note: 'First snow in Central Park. Walked the Brooklyn Bridge in the cold. Pizza is better here.',
		photos: [p('5-1', 'nyc-central-park'), p('5-2', 'nyc-brooklyn'), p('5-3', 'nyc-times-square')],
		coverPhoto: p('5-1', 'nyc-central-park'),
		participants: [
			{ id: 'f2', name: 'Marco Rossi', gender: 'male', avatar_index: 0, status: 'confirmed' },
			{ id: 'f3', name: 'Jake Thompson', gender: 'male', avatar_index: 2, status: 'confirmed' },
		],
		latitude: 40.7829,
		longitude: -73.9654,
	},
	{
		id: '6',
		status: 'planned',
		title: 'Santorini Summer',
		city: 'Santorini',
		country: 'Greece',
		flag: '🇬🇷',
		startDate: '2026-07-10',
		endDate: '2026-07-17',
		photoCount: 0,
		photos: [],
		note: 'Been dreaming about this for years. Oia at sunset, fresh seafood, the caldera views.',
		participants: [
			{ id: 'f1', name: 'Emma Wilson', gender: 'female', avatar_index: 0, status: 'confirmed' },
			{ id: 'f3', name: 'Jake Thompson', gender: 'male', avatar_index: 2, status: 'confirmed' },
			{ id: 'f4', name: 'Sophia Chen', gender: 'female', avatar_index: 3, status: 'confirmed' },
		],
		latitude: 36.3932,
		longitude: 25.4615,
		timelineItems: santoriniTimeline,
	},
];
