import type { MockTrip } from '@/types/trip';

const p = (id: string, seed: string) => ({ id, url: `https://picsum.photos/seed/${seed}/800/600` });

export const MOCK_TRIPS: MockTrip[] = [
	{
		id: '1',
		title: 'Roman Holiday',
		city: 'Rome',
		country: 'Italy',
		flag: '🇮🇹',
		startDate: '2025-03-15',
		endDate: '2025-03-22',
		photoCount: 47,
		note: 'The Colosseum at sunset was unbelievable. Best carbonara of my life. Spent way too long at the Forum.',
		photos: [p('1-1', 'rome-forum'), p('1-2', 'rome-colosseum'), p('1-3', 'rome-trevi')],
		coverPhoto: p('1-1', 'rome-forum'),
		participants: [
			{ id: 'f1', name: 'Emma Wilson', gender: 'female', avatarIndex: 0, status: 'confirmed' },
			{ id: 'f2', name: 'Marco Rossi', gender: 'male', avatarIndex: 0, status: 'confirmed' },
		],
	},
	{
		id: '2',
		title: 'Lisbon in Bloom',
		city: 'Lisbon',
		country: 'Portugal',
		flag: '🇵🇹',
		startDate: '2025-05-01',
		endDate: '2025-05-07',
		photoCount: 31,
		note: 'Tram 28 through the old city. Pastéis de nata still warm from the bakery. Views from the castle were worth every step.',
		photos: [p('2-1', 'lisbon-tram'), p('2-2', 'lisbon-alfama'), p('2-3', 'lisbon-belem')],
		coverPhoto: p('2-1', 'lisbon-tram'),
		participants: [{ id: 'f3', name: 'Jake Thompson', gender: 'male', avatarIndex: 2, status: 'confirmed' }],
	},
	{
		id: '3',
		title: 'Tokyo Nights',
		city: 'Tokyo',
		country: 'Japan',
		flag: '🇯🇵',
		startDate: '2024-10-10',
		endDate: '2024-10-20',
		photoCount: 89,
		note: 'Shibuya at 2am will never leave my mind. Tsukiji breakfast. Could have stayed forever.',
		photos: [p('3-1', 'tokyo-shibuya'), p('3-2', 'tokyo-temple'), p('3-3', 'tokyo-night'), p('3-4', 'tokyo-street')],
		coverPhoto: p('3-1', 'tokyo-shibuya'),
		participants: [
			{ id: 'f1', name: 'Emma Wilson', gender: 'female', avatarIndex: 0, status: 'confirmed' },
			{ id: 'f4', name: 'Sophia Chen', gender: 'female', avatarIndex: 3, status: 'confirmed' },
			{ id: 'f5', name: 'Lucas Müller', gender: 'male', avatarIndex: 5, status: 'confirmed' },
		],
	},
	{
		id: '4',
		title: 'Barcelona Weekend',
		city: 'Barcelona',
		country: 'Spain',
		flag: '🇪🇸',
		startDate: '2025-01-10',
		endDate: '2025-01-12',
		photoCount: 23,
		note: 'Gaudí changed how I see architecture forever. Beach day after Sagrada Família.',
		photos: [p('4-1', 'barcelona-sagrada'), p('4-2', 'barcelona-beach')],
		coverPhoto: p('4-1', 'barcelona-sagrada'),
		participants: [],
	},
	{
		id: '5',
		title: 'NYC Winter',
		city: 'New York',
		country: 'United States',
		flag: '🇺🇸',
		startDate: '2024-12-20',
		endDate: '2024-12-27',
		photoCount: 62,
		note: 'First snow in Central Park. Walked the Brooklyn Bridge in the cold. Pizza is better here.',
		photos: [p('5-1', 'nyc-central-park'), p('5-2', 'nyc-brooklyn'), p('5-3', 'nyc-times-square')],
		coverPhoto: p('5-1', 'nyc-central-park'),
		participants: [
			{ id: 'f2', name: 'Marco Rossi', gender: 'male', avatarIndex: 0, status: 'confirmed' },
			{ id: 'f3', name: 'Jake Thompson', gender: 'male', avatarIndex: 2, status: 'confirmed' },
		],
	},
];
